name: nemo-voice
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.12=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - absl-py==2.3.1
    - accelerate==1.10.1
    - accelerated-scan==0.2.0
    - addict==2.4.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - alabaster==1.0.0
    - alembic==1.16.5
    - aniso8601==10.0.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - asciitree==0.3.3
    - astor==0.8.1
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrdict==2.0.1
    - attrs==25.3.0
    - audioread==3.0.1
    - av==15.1.0
    - babel==2.17.0
    - backports-datetime-fromisoformat==2.0.3
    - bcrypt==5.0.0
    - beautifulsoup4==4.13.1
    - bitsandbytes==0.46.0
    - black==24.10.0
    - blake3==1.0.7
    - blinker==1.9.0
    - boto3==1.40.44
    - botocore==1.40.44
    - braceexpand==0.1.7
    - bracex==2.6
    - cachetools==6.2.0
    - catalogue==2.0.10
    - cbor2==5.7.0
    - cdifflib==1.2.6
    - certifi==2025.8.3
    - cffi==2.0.0
    - chardet==5.2.0
    - charset-normalizer==3.4.3
    - click==8.3.0
    - clip==0.2.0
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - colorlog==6.9.0
    - compressed-tensors==0.10.2
    - contextlib2==21.6.0
    - contourpy==1.3.2
    - coverage==7.10.7
    - cryptography==42.0.8
    - cupy-cuda12x==13.6.0
    - cycler==0.12.1
    - cytoolz==1.0.1
    - dataproperty==1.1.0
    - datasets==4.1.1
    - decorator==5.2.1
    - decord==0.6.0
    - defusedxml==0.7.1
    - deprecated==1.2.18
    - depyf==0.19.0
    - diffusers==0.35.1
    - dill==0.4.0
    - diskcache==5.6.3
    - distro==1.9.0
    - dnspython==2.8.0
    - docker==7.1.0
    - docopt==0.6.2
    - docstring-parser==0.17.0
    - docutils==0.21.2
    - editdistance==0.8.1
    - einops==0.8.1
    - einops-exts==0.0.4
    - email-validator==2.3.0
    - evaluate==0.4.6
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fabric==3.2.2
    - faiss-cpu==1.12.0
    - fastapi==0.118.0
    - fastapi-cli==0.0.13
    - fastapi-cloud-cli==0.3.0
    - fasteners==0.20
    - fastrlock==0.8.3
    - fiddle==0.3.0
    - filelock==3.19.1
    - flask==3.1.2
    - flask-restful==0.3.10
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - frozendict==2.4.6
    - frozenlist==1.7.0
    - fsspec==2024.12.0
    - ftfy==6.3.1
    - future==1.0.0
    - gdown==5.2.0
    - gguf==0.17.1
    - gitdb==4.0.12
    - gitpython==3.1.45
    - graphviz==0.21
    - greenlet==3.2.4
    - grpcio==1.75.1
    - h11==0.16.0
    - h2==4.3.0
    - h5py==3.14.0
    - hf-xet==1.1.10
    - hpack==4.1.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.35.3
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - hyperframe==6.1.0
    - idna==3.10
    - ijson==3.4.0
    - imageio==2.37.0
    - imagesize==1.4.1
    - immutabledict==4.2.0
    - importlib-metadata==8.7.0
    - indic-numtowords==1.1.0
    - inflect==7.5.0
    - iniconfig==2.1.0
    - inquirerpy==0.3.4
    - interegular==0.3.3
    - intervaltree==3.1.0
    - invoke==2.2.0
    - ipython==8.37.0
    - isort==5.13.2
    - itsdangerous==2.2.0
    - janome==0.5.0
    - jedi==0.19.2
    - jieba==0.42.1
    - jinja2==3.1.6
    - jiter==0.11.0
    - jiwer==3.1.0
    - jmespath==1.0.1
    - joblib==1.5.2
    - jsonlines==4.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kaldi-python-io==1.2.2
    - kaldialign==0.9.1
    - kiwisolver==1.4.9
    - kornia==0.8.1
    - kornia-rs==0.1.9
    - langdetect==1.0.9
    - lark==1.2.2
    - latexcodec==3.0.1
    - lazy-loader==0.4
    - ledoc-ui==0.1.0
    - leptonai==0.26.6
    - lhotse==1.31.1
    - libcst==1.8.5
    - librosa==0.11.0
    - lightning==2.4.0
    - lightning-utilities==0.15.2
    - lilcom==1.8.1
    - llguidance==0.7.30
    - llvmlite==0.44.0
    - lm-format-enforcer==0.10.12
    - loguru==0.7.3
    - lxml==6.0.2
    - mako==1.3.10
    - markdown==3.9
    - markdown-it-py==4.0.0
    - markdown2==2.5.4
    - markupsafe==3.0.3
    - marshmallow==4.0.1
    - matplotlib==3.10.6
    - matplotlib-inline==0.1.7
    - mbstrdecoder==1.1.4
    - mdurl==0.1.2
    - mediapy==1.1.6
    - megatron-core==0.13.1
    - megatron-energon==5.2.0
    - mistral-common==1.8.5
    - ml-dtypes==0.5.3
    - more-itertools==10.8.0
    - mpmath==1.3.0
    - msgpack==1.1.1
    - msgspec==0.19.0
    - multi-storage-client==0.31.0
    - multidict==6.6.4
    - multiprocess==0.70.16
    - mypy-extensions==1.1.0
    - nemo-run==0.5.0
    - nemo-text-processing==1.1.0
    - nemo-toolkit==2.5.0rc0
    - nerfacc==0.5.3
    - networkx==3.4.2
    - ninja==1.13.0
    - nltk==3.9.2
    - num2words==0.5.14
    - numba==0.61.2
    - numcodecs==0.13.1
    - numexpr==2.13.1
    - numpy==1.26.4
    - nv-one-logger-core==2.1.0
    - nv-one-logger-pytorch-lightning-integration==2.1.0
    - nv-one-logger-training-telemetry==2.1.0
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-lm-eval==25.6.1
    - nvidia-ml-py==13.580.82
    - nvidia-modelopt==0.35.0
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - nvidia-resiliency-ext==0.4.1
    - nvtx==0.2.13
    - omegaconf==2.3.0
    - onnx==1.19.0
    - onnxruntime==1.23.0
    - open-clip-torch==2.24.0
    - openai==1.99.1
    - openai-harmony==0.0.4
    - opencc==1.1.9
    - opencv-python-headless==4.11.0.86
    - opentelemetry-api==1.37.0
    - optuna==4.5.0
    - orjson==3.11.3
    - outlines-core==0.2.10
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.3.3
    - pangu==4.0.6.1
    - parameterized==0.9.0
    - paramiko==4.0.0
    - parso==0.8.5
    - partial-json-parser==0.2.1.1.post6
    - pathspec==0.12.1
    - pathvalidate==3.3.1
    - peft==0.17.1
    - pesq==0.0.4
    - pexpect==4.9.0
    - pfzy==0.3.4
    - pillow==11.3.0
    - pipecat-ai==0.0.84
    - platformdirs==4.4.0
    - pluggy==1.6.0
    - pooch==1.8.2
    - portalocker==3.2.0
    - prettytable==3.16.0
    - progress==1.6.1
    - prometheus-client==0.23.1
    - prometheus-fastapi-instrumentator==7.0.0
    - prompt-toolkit==3.0.52
    - propcache==0.3.2
    - protobuf==5.29.5
    - psutil==7.1.0
    - ptyprocess==0.7.0
    - pulp==3.3.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyannote-core==5.0.0
    - pyannote-database==5.1.3
    - pyannote-metrics==3.2.1
    - pyarrow==21.0.0
    - pybase64==1.4.2
    - pybind11==3.0.1
    - pybtex==0.25.1
    - pybtex-docutils==1.0.3
    - pycountry==24.6.1
    - pycparser==2.23
    - pydantic==2.11.9
    - pydantic-core==2.33.2
    - pydantic-extra-types==2.10.5
    - pydantic-settings==2.11.0
    - pydub==0.25.1
    - pygments==2.19.2
    - pyloudnorm==0.1.1
    - pynacl==1.6.0
    - pynini==2.1.6.post1
    - pynvml==13.0.1
    - pyparsing==3.2.5
    - pypinyin==0.55.0
    - pypinyin-dict==0.9.0
    - pyre-extensions==0.0.32
    - pysocks==1.7.1
    - pystoi==0.4.1
    - pytablewriter==1.2.1
    - pytest==8.4.2
    - pytest-httpserver==1.1.3
    - pytest-mock==3.15.1
    - pytest-runner==6.0.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.1
    - python-json-logger==3.3.0
    - python-multipart==0.0.20
    - pytorch-lightning==2.5.5
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - qwen-vl-utils==0.0.14
    - rapidfuzz==3.14.1
    - ray==2.49.2
    - referencing==0.36.2
    - regex==2025.9.18
    - requests==2.32.5
    - resampy==0.4.3
    - rich==14.1.0
    - rich-toolkit==0.15.1
    - rignore==0.7.0
    - rouge-score==0.1.2
    - rpds-py==0.27.1
    - ruamel-yaml==0.18.15
    - ruamel-yaml-clib==0.2.14
    - s3fs==0.4.2
    - s3transfer==0.14.0
    - sacrebleu==2.5.1
    - sacremoses==0.1.1
    - safetensors==0.6.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentence-transformers==5.1.1
    - sentencepiece==0.2.1
    - sentry-sdk==2.39.0
    - setproctitle==1.3.7
    - setuptools==80.9.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - snowballstemmer==3.0.1
    - sortedcontainers==2.4.0
    - soundfile==0.13.1
    - soupsieve==2.8
    - sox==1.5.0
    - soxr==0.5.0.post1
    - sphinx==8.1.3
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-bibtex==2.6.5
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sqlalchemy==2.0.43
    - stack-data==0.6.3
    - starlette==0.48.0
    - strenum==0.4.15
    - sympy==1.14.0
    - tabledata==1.3.4
    - tabulate==0.9.0
    - taming-transformers==0.0.1
    - tcolorpy==0.1.7
    - tenacity==9.1.2
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.71
    - text-unidecode==1.3
    - textdistance==4.6.3
    - threadpoolctl==3.6.0
    - tiktoken==0.7.0
    - timm==1.0.20
    - tokenizers==0.22.1
    - toml==0.10.2
    - tomli==2.2.1
    - toolz==1.0.0
    - torch==2.7.1
    - torchaudio==2.7.1
    - torchdiffeq==0.2.5
    - torchmetrics==1.8.2
    - torchprofile==0.0.4
    - torchsde==0.2.6
    - torchvision==0.22.1
    - torchx==0.7.0
    - tqdm==4.67.1
    - tqdm-multiprocess==0.0.11
    - traitlets==5.14.3
    - trampoline==0.1.2
    - transformers==4.56.1
    - tree-sitter==0.25.2
    - tree-sitter-python==0.25.0
    - trimesh==4.8.3
    - triton==3.3.1
    - typeguard==4.4.4
    - typepy==1.3.4
    - typer==0.19.2
    - typing-extensions==4.15.0
    - typing-inspect==0.9.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - ujson==5.11.0
    - urllib3==1.26.20
    - uvicorn==0.37.0
    - uvloop==0.21.0
    - vllm==0.10.1
    - wait-for2==0.4.1
    - wandb==0.22.1
    - watchfiles==1.1.0
    - wcmatch==10.1
    - wcwidth==0.2.14
    - webdataset==1.0.2
    - websockets==15.0.1
    - werkzeug==3.1.3
    - wget==3.2
    - whisper-normalizer==0.1.12
    - word2number==1.1
    - wrapt==1.17.3
    - xattr==1.2.0
    - xformers==0.0.31
    - xgrammar==0.1.21
    - xxhash==3.6.0
    - yarl==1.20.1
    - zarr==2.18.3
    - zipp==3.23.0
    - zstandard==0.25.0
prefix: /home/heh/anaconda3/envs/nemo2
